module.exports = {
	"13": {
		"id": 13,
		"name": "Wrap",
		"type": "normal",
		"power": 60,
		"duration": 2900,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 60,
		"pvpEnergy": 45
	},
	"14": {
		"id": 14,
		"name": "Hyper Beam",
		"type": "normal",
		"power": 150,
		"duration": 3800,
		"energy": 100,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 150,
		"pvpEnergy": 80
	},
	"16": {
		"id": 16,
		"name": "Dark Pulse",
		"type": "dark",
		"power": 80,
		"duration": 3000,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 80,
		"pvpEnergy": 50
	},
	"18": {
		"id": 18,
		"name": "Sludge",
		"type": "poison",
		"power": 50,
		"duration": 2100,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 50,
		"pvpEnergy": 40
	},
	"20": {
		"id": 20,
		"name": "Vise Grip",
		"type": "normal",
		"power": 35,
		"duration": 1900,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 40,
		"pvpEnergy": 40
	},
	"21": {
		"id": 21,
		"name": "Flame Wheel",
		"type": "fire",
		"power": 60,
		"duration": 2700,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 60,
		"pvpEnergy": 55
	},
	"22": {
		"id": 22,
		"name": "Megahorn",
		"type": "bug",
		"power": 110,
		"duration": 2200,
		"energy": 100,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 100,
		"pvpEnergy": 55
	},
	"24": {
		"id": 24,
		"name": "Flamethrower",
		"type": "fire",
		"power": 70,
		"duration": 2200,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 90,
		"pvpEnergy": 55
	},
	"26": {
		"id": 26,
		"name": "Dig",
		"type": "ground",
		"power": 100,
		"duration": 4700,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 100,
		"pvpEnergy": 80
	},
	"28": {
		"id": 28,
		"name": "Cross Chop",
		"type": "fighting",
		"power": 50,
		"duration": 1500,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 50,
		"pvpEnergy": 35
	},
	"30": {
		"id": 30,
		"name": "Psybeam",
		"type": "psychic",
		"power": 70,
		"duration": 3200,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 70,
		"pvpEnergy": 60
	},
	"31": {
		"id": 31,
		"name": "Earthquake",
		"type": "ground",
		"power": 140,
		"duration": 3600,
		"energy": 100,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 120,
		"pvpEnergy": 65
	},
	"32": {
		"id": 32,
		"name": "Stone Edge",
		"type": "rock",
		"power": 100,
		"duration": 2300,
		"energy": 100,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 100,
		"pvpEnergy": 55
	},
	"33": {
		"id": 33,
		"name": "Ice Punch",
		"type": "ice",
		"power": 50,
		"duration": 1900,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 55,
		"pvpEnergy": 40
	},
	"35": {
		"id": 35,
		"name": "Discharge",
		"type": "electric",
		"power": 65,
		"duration": 2500,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 65,
		"pvpEnergy": 45
	},
	"36": {
		"id": 36,
		"name": "Flash Cannon",
		"type": "steel",
		"power": 100,
		"duration": 2700,
		"energy": 100,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 110,
		"pvpEnergy": 70
	},
	"38": {
		"id": 38,
		"name": "Drill Peck",
		"type": "flying",
		"power": 65,
		"duration": 2300,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 65,
		"pvpEnergy": 40
	},
	"39": {
		"id": 39,
		"name": "Ice Beam",
		"type": "ice",
		"power": 90,
		"duration": 3300,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 90,
		"pvpEnergy": 55
	},
	"40": {
		"id": 40,
		"name": "Blizzard",
		"type": "ice",
		"power": 130,
		"duration": 3100,
		"energy": 100,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 140,
		"pvpEnergy": 75
	},
	"42": {
		"id": 42,
		"name": "Heat Wave",
		"type": "fire",
		"power": 95,
		"duration": 3000,
		"energy": 100,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 95,
		"pvpEnergy": 75
	},
	"45": {
		"id": 45,
		"name": "Aerial Ace",
		"type": "flying",
		"power": 55,
		"duration": 2400,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 55,
		"pvpEnergy": 45
	},
	"46": {
		"id": 46,
		"name": "Drill Run",
		"type": "ground",
		"power": 80,
		"duration": 2800,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 80,
		"pvpEnergy": 45
	},
	"47": {
		"id": 47,
		"name": "Petal Blizzard",
		"type": "grass",
		"power": 110,
		"duration": 2600,
		"energy": 100,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 110,
		"pvpEnergy": 65
	},
	"49": {
		"id": 49,
		"name": "Bug Buzz",
		"type": "bug",
		"power": 90,
		"duration": 3700,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 90,
		"pvpEnergy": 60
	},
	"50": {
		"id": 50,
		"name": "Poison Fang",
		"type": "poison",
		"power": 35,
		"duration": 1700,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 40,
		"pvpEnergy": 35
	},
	"51": {
		"id": 51,
		"name": "Night Slash",
		"type": "dark",
		"power": 50,
		"duration": 2200,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 50,
		"pvpEnergy": 35
	},
	"53": {
		"id": 53,
		"name": "Bubble Beam",
		"type": "water",
		"power": 45,
		"duration": 1900,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 25,
		"pvpEnergy": 40
	},
	"54": {
		"id": 54,
		"name": "Submission",
		"type": "fighting",
		"power": 60,
		"duration": 2200,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 60,
		"pvpEnergy": 50
	},
	"56": {
		"id": 56,
		"name": "Low Sweep",
		"type": "fighting",
		"power": 40,
		"duration": 1900,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 40,
		"pvpEnergy": 40
	},
	"57": {
		"id": 57,
		"name": "Aqua Jet",
		"type": "water",
		"power": 45,
		"duration": 2600,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 45,
		"pvpEnergy": 45
	},
	"58": {
		"id": 58,
		"name": "Aqua Tail",
		"type": "water",
		"power": 50,
		"duration": 1900,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 50,
		"pvpEnergy": 35
	},
	"59": {
		"id": 59,
		"name": "Seed Bomb",
		"type": "grass",
		"power": 55,
		"duration": 2100,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 55,
		"pvpEnergy": 40
	},
	"60": {
		"id": 60,
		"name": "Psyshock",
		"type": "psychic",
		"power": 65,
		"duration": 2700,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 70,
		"pvpEnergy": 45
	},
	"62": {
		"id": 62,
		"name": "Ancient Power",
		"type": "rock",
		"power": 70,
		"duration": 3500,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 45,
		"pvpEnergy": 45
	},
	"63": {
		"id": 63,
		"name": "Rock Tomb",
		"type": "rock",
		"power": 70,
		"duration": 3200,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 70,
		"pvpEnergy": 60
	},
	"64": {
		"id": 64,
		"name": "Rock Slide",
		"type": "rock",
		"power": 80,
		"duration": 2700,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 80,
		"pvpEnergy": 45
	},
	"65": {
		"id": 65,
		"name": "Power Gem",
		"type": "rock",
		"power": 80,
		"duration": 2900,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 80,
		"pvpEnergy": 60
	},
	"67": {
		"id": 67,
		"name": "Shadow Punch",
		"type": "ghost",
		"power": 40,
		"duration": 1700,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 40,
		"pvpEnergy": 35
	},
	"69": {
		"id": 69,
		"name": "Ominous Wind",
		"type": "ghost",
		"power": 50,
		"duration": 2300,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 45,
		"pvpEnergy": 45
	},
	"70": {
		"id": 70,
		"name": "Shadow Ball",
		"type": "ghost",
		"power": 100,
		"duration": 3000,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 100,
		"pvpEnergy": 55
	},
	"72": {
		"id": 72,
		"name": "Magnet Bomb",
		"type": "steel",
		"power": 70,
		"duration": 2800,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 70,
		"pvpEnergy": 45
	},
	"74": {
		"id": 74,
		"name": "Iron Head",
		"type": "steel",
		"power": 60,
		"duration": 1900,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 70,
		"pvpEnergy": 50
	},
	"77": {
		"id": 77,
		"name": "Thunder Punch",
		"type": "electric",
		"power": 45,
		"duration": 1800,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 55,
		"pvpEnergy": 40
	},
	"78": {
		"id": 78,
		"name": "Thunder",
		"type": "electric",
		"power": 100,
		"duration": 2400,
		"energy": 100,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 100,
		"pvpEnergy": 60
	},
	"79": {
		"id": 79,
		"name": "Thunderbolt",
		"type": "electric",
		"power": 80,
		"duration": 2500,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 90,
		"pvpEnergy": 55
	},
	"80": {
		"id": 80,
		"name": "Twister",
		"type": "dragon",
		"power": 45,
		"duration": 2800,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 45,
		"pvpEnergy": 45
	},
	"82": {
		"id": 82,
		"name": "Dragon Pulse",
		"type": "dragon",
		"power": 90,
		"duration": 3600,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 90,
		"pvpEnergy": 60
	},
	"83": {
		"id": 83,
		"name": "Dragon Claw",
		"type": "dragon",
		"power": 50,
		"duration": 1700,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 50,
		"pvpEnergy": 35
	},
	"84": {
		"id": 84,
		"name": "Disarming Voice",
		"type": "fairy",
		"power": 70,
		"duration": 3900,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 70,
		"pvpEnergy": 45
	},
	"85": {
		"id": 85,
		"name": "Draining Kiss",
		"type": "fairy",
		"power": 60,
		"duration": 2600,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 60,
		"pvpEnergy": 55
	},
	"86": {
		"id": 86,
		"name": "Dazzling Gleam",
		"type": "fairy",
		"power": 100,
		"duration": 3500,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 110,
		"pvpEnergy": 70
	},
	"87": {
		"id": 87,
		"name": "Moonblast",
		"type": "fairy",
		"power": 130,
		"duration": 3900,
		"energy": 100,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 110,
		"pvpEnergy": 60
	},
	"88": {
		"id": 88,
		"name": "Play Rough",
		"type": "fairy",
		"power": 90,
		"duration": 2900,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 90,
		"pvpEnergy": 60
	},
	"89": {
		"id": 89,
		"name": "Cross Poison",
		"type": "poison",
		"power": 40,
		"duration": 1500,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 40,
		"pvpEnergy": 35
	},
	"90": {
		"id": 90,
		"name": "Sludge Bomb",
		"type": "poison",
		"power": 80,
		"duration": 2300,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 80,
		"pvpEnergy": 50
	},
	"91": {
		"id": 91,
		"name": "Sludge Wave",
		"type": "poison",
		"power": 110,
		"duration": 3200,
		"energy": 100,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 110,
		"pvpEnergy": 65
	},
	"92": {
		"id": 92,
		"name": "Gunk Shot",
		"type": "poison",
		"power": 130,
		"duration": 3100,
		"energy": 100,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 130,
		"pvpEnergy": 75
	},
	"94": {
		"id": 94,
		"name": "Bone Club",
		"type": "ground",
		"power": 40,
		"duration": 1600,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 40,
		"pvpEnergy": 35
	},
	"95": {
		"id": 95,
		"name": "Bulldoze",
		"type": "ground",
		"power": 80,
		"duration": 3500,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 80,
		"pvpEnergy": 60
	},
	"96": {
		"id": 96,
		"name": "Mud Bomb",
		"type": "ground",
		"power": 55,
		"duration": 2300,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 55,
		"pvpEnergy": 40
	},
	"99": {
		"id": 99,
		"name": "Signal Beam",
		"type": "bug",
		"power": 75,
		"duration": 2900,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 75,
		"pvpEnergy": 55
	},
	"100": {
		"id": 100,
		"name": "X-Scissor",
		"type": "bug",
		"power": 45,
		"duration": 1600,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 45,
		"pvpEnergy": 35
	},
	"101": {
		"id": 101,
		"name": "Flame Charge",
		"type": "fire",
		"power": 70,
		"duration": 3800,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 65,
		"pvpEnergy": 50
	},
	"102": {
		"id": 102,
		"name": "Flame Burst",
		"type": "fire",
		"power": 70,
		"duration": 2600,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 70,
		"pvpEnergy": 55
	},
	"103": {
		"id": 103,
		"name": "Fire Blast",
		"type": "fire",
		"power": 140,
		"duration": 4200,
		"energy": 100,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 140,
		"pvpEnergy": 80
	},
	"104": {
		"id": 104,
		"name": "Brine",
		"type": "water",
		"power": 60,
		"duration": 2300,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 60,
		"pvpEnergy": 50
	},
	"105": {
		"id": 105,
		"name": "Water Pulse",
		"type": "water",
		"power": 70,
		"duration": 3200,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 70,
		"pvpEnergy": 60
	},
	"106": {
		"id": 106,
		"name": "Scald",
		"type": "water",
		"power": 80,
		"duration": 3700,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 80,
		"pvpEnergy": 60
	},
	"107": {
		"id": 107,
		"name": "Hydro Pump",
		"type": "water",
		"power": 130,
		"duration": 3300,
		"energy": 100,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 130,
		"pvpEnergy": 75
	},
	"108": {
		"id": 108,
		"name": "Psychic",
		"type": "psychic",
		"power": 90,
		"duration": 2800,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 90,
		"pvpEnergy": 55
	},
	"109": {
		"id": 109,
		"name": "Psystrike",
		"type": "psychic",
		"power": 90,
		"duration": 2300,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 90,
		"pvpEnergy": 45
	},
	"111": {
		"id": 111,
		"name": "Icy Wind",
		"type": "ice",
		"power": 60,
		"duration": 3300,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 60,
		"pvpEnergy": 45
	},
	"115": {
		"id": 115,
		"name": "Fire Punch",
		"type": "fire",
		"power": 55,
		"duration": 2200,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 55,
		"pvpEnergy": 40
	},
	"116": {
		"id": 116,
		"name": "Solar Beam",
		"type": "grass",
		"power": 180,
		"duration": 4900,
		"energy": 100,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 150,
		"pvpEnergy": 80
	},
	"117": {
		"id": 117,
		"name": "Leaf Blade",
		"type": "grass",
		"power": 70,
		"duration": 2400,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 70,
		"pvpEnergy": 35
	},
	"118": {
		"id": 118,
		"name": "Power Whip",
		"type": "grass",
		"power": 90,
		"duration": 2600,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 90,
		"pvpEnergy": 50
	},
	"121": {
		"id": 121,
		"name": "Air Cutter",
		"type": "flying",
		"power": 60,
		"duration": 2700,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 60,
		"pvpEnergy": 55
	},
	"122": {
		"id": 122,
		"name": "Hurricane",
		"type": "flying",
		"power": 110,
		"duration": 2700,
		"energy": 100,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 110,
		"pvpEnergy": 65
	},
	"123": {
		"id": 123,
		"name": "Brick Break",
		"type": "fighting",
		"power": 40,
		"duration": 1600,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 40,
		"pvpEnergy": 35
	},
	"125": {
		"id": 125,
		"name": "Swift",
		"type": "normal",
		"power": 60,
		"duration": 2800,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 60,
		"pvpEnergy": 55
	},
	"126": {
		"id": 126,
		"name": "Horn Attack",
		"type": "normal",
		"power": 40,
		"duration": 1850,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 40,
		"pvpEnergy": 35
	},
	"127": {
		"id": 127,
		"name": "Stomp",
		"type": "normal",
		"power": 55,
		"duration": 1700,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 55,
		"pvpEnergy": 40
	},
	"129": {
		"id": 129,
		"name": "Hyper Fang",
		"type": "normal",
		"power": 80,
		"duration": 2500,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 80,
		"pvpEnergy": 50
	},
	"131": {
		"id": 131,
		"name": "Body Slam",
		"type": "normal",
		"power": 50,
		"duration": 1900,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 60,
		"pvpEnergy": 35
	},
	"133": {
		"id": 133,
		"name": "Struggle",
		"type": "normal",
		"power": 35,
		"duration": 2200,
		"energy": 0,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 35,
		"pvpEnergy": 100
	},
	"200": {
		"id": 200,
		"name": "Fury Cutter",
		"type": "bug",
		"power": 3,
		"duration": 400,
		"energy": 6,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 2,
		"pvpEnergy": 4
	},
	"201": {
		"id": 201,
		"name": "Bug Bite",
		"type": "bug",
		"power": 5,
		"duration": 500,
		"energy": 6,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 3,
		"pvpEnergy": 3
	},
	"202": {
		"id": 202,
		"name": "Bite",
		"type": "dark",
		"power": 6,
		"duration": 500,
		"energy": 4,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 4,
		"pvpEnergy": 2
	},
	"203": {
		"id": 203,
		"name": "Sucker Punch",
		"type": "dark",
		"power": 7,
		"duration": 700,
		"energy": 8,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 5,
		"pvpEnergy": 7
	},
	"204": {
		"id": 204,
		"name": "Dragon Breath",
		"type": "dragon",
		"power": 6,
		"duration": 500,
		"energy": 4,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 4,
		"pvpEnergy": 3
	},
	"205": {
		"id": 205,
		"name": "Thunder Shock",
		"type": "electric",
		"power": 5,
		"duration": 600,
		"energy": 8,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 3,
		"pvpEnergy": 9
	},
	"206": {
		"id": 206,
		"name": "Spark",
		"type": "electric",
		"power": 6,
		"duration": 700,
		"energy": 9,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 4,
		"pvpEnergy": 8
	},
	"207": {
		"id": 207,
		"name": "Low Kick",
		"type": "fighting",
		"power": 6,
		"duration": 600,
		"energy": 6,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 4,
		"pvpEnergy": 5
	},
	"208": {
		"id": 208,
		"name": "Karate Chop",
		"type": "fighting",
		"power": 8,
		"duration": 800,
		"energy": 10,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 5,
		"pvpEnergy": 7
	},
	"209": {
		"id": 209,
		"name": "Ember",
		"type": "fire",
		"power": 10,
		"duration": 1000,
		"energy": 10,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 6,
		"pvpEnergy": 6
	},
	"210": {
		"id": 210,
		"name": "Wing Attack",
		"type": "flying",
		"power": 8,
		"duration": 800,
		"energy": 9,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 5,
		"pvpEnergy": 7
	},
	"211": {
		"id": 211,
		"name": "Peck",
		"type": "flying",
		"power": 10,
		"duration": 1000,
		"energy": 10,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 6,
		"pvpEnergy": 5
	},
	"212": {
		"id": 212,
		"name": "Lick",
		"type": "ghost",
		"power": 5,
		"duration": 500,
		"energy": 6,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 3,
		"pvpEnergy": 3
	},
	"213": {
		"id": 213,
		"name": "Shadow Claw",
		"type": "ghost",
		"power": 9,
		"duration": 700,
		"energy": 6,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 6,
		"pvpEnergy": 8
	},
	"214": {
		"id": 214,
		"name": "Vine Whip",
		"type": "grass",
		"power": 7,
		"duration": 600,
		"energy": 6,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 5,
		"pvpEnergy": 8
	},
	"215": {
		"id": 215,
		"name": "Razor Leaf",
		"type": "grass",
		"power": 13,
		"duration": 1000,
		"energy": 7,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 11,
		"pvpEnergy": 4
	},
	"216": {
		"id": 216,
		"name": "Mud Shot",
		"type": "ground",
		"power": 5,
		"duration": 600,
		"energy": 7,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 3,
		"pvpEnergy": 9
	},
	"217": {
		"id": 217,
		"name": "Ice Shard",
		"type": "ice",
		"power": 12,
		"duration": 1200,
		"energy": 12,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 9,
		"pvpEnergy": 10
	},
	"218": {
		"id": 218,
		"name": "Frost Breath",
		"type": "ice",
		"power": 10,
		"duration": 900,
		"energy": 8,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 7,
		"pvpEnergy": 5
	},
	"219": {
		"id": 219,
		"name": "Quick Attack",
		"type": "normal",
		"power": 8,
		"duration": 800,
		"energy": 10,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 5,
		"pvpEnergy": 7
	},
	"220": {
		"id": 220,
		"name": "Scratch",
		"type": "normal",
		"power": 6,
		"duration": 500,
		"energy": 4,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 4,
		"pvpEnergy": 2
	},
	"221": {
		"id": 221,
		"name": "Tackle",
		"type": "normal",
		"power": 5,
		"duration": 500,
		"energy": 5,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 3,
		"pvpEnergy": 2
	},
	"222": {
		"id": 222,
		"name": "Pound",
		"type": "normal",
		"power": 7,
		"duration": 600,
		"energy": 6,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 5,
		"pvpEnergy": 4
	},
	"223": {
		"id": 223,
		"name": "Cut",
		"type": "normal",
		"power": 5,
		"duration": 500,
		"energy": 5,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 3,
		"pvpEnergy": 2
	},
	"224": {
		"id": 224,
		"name": "Poison Jab",
		"type": "poison",
		"power": 10,
		"duration": 800,
		"energy": 7,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 6,
		"pvpEnergy": 7
	},
	"225": {
		"id": 225,
		"name": "Acid",
		"type": "poison",
		"power": 9,
		"duration": 800,
		"energy": 8,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 6,
		"pvpEnergy": 5
	},
	"226": {
		"id": 226,
		"name": "Psycho Cut",
		"type": "psychic",
		"power": 5,
		"duration": 600,
		"energy": 8,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 3,
		"pvpEnergy": 9
	},
	"227": {
		"id": 227,
		"name": "Rock Throw",
		"type": "rock",
		"power": 12,
		"duration": 900,
		"energy": 7,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 8,
		"pvpEnergy": 5
	},
	"228": {
		"id": 228,
		"name": "Metal Claw",
		"type": "steel",
		"power": 8,
		"duration": 700,
		"energy": 7,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 5,
		"pvpEnergy": 6
	},
	"229": {
		"id": 229,
		"name": "Bullet Punch",
		"type": "steel",
		"power": 9,
		"duration": 900,
		"energy": 10,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 6,
		"pvpEnergy": 7
	},
	"230": {
		"id": 230,
		"name": "Water Gun",
		"type": "water",
		"power": 5,
		"duration": 500,
		"energy": 5,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 3,
		"pvpEnergy": 3
	},
	"231": {
		"id": 231,
		"name": "Splash",
		"type": "water",
		"power": 0,
		"duration": 1730,
		"energy": 20,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 0,
		"pvpEnergy": 12
	},
	"233": {
		"id": 233,
		"name": "Mud-Slap",
		"type": "ground",
		"power": 18,
		"duration": 1400,
		"energy": 12,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 11,
		"pvpEnergy": 8
	},
	"234": {
		"id": 234,
		"name": "Zen Headbutt",
		"type": "psychic",
		"power": 12,
		"duration": 1100,
		"energy": 10,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 8,
		"pvpEnergy": 6
	},
	"235": {
		"id": 235,
		"name": "Confusion",
		"type": "psychic",
		"power": 20,
		"duration": 1600,
		"energy": 15,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 16,
		"pvpEnergy": 12
	},
	"236": {
		"id": 236,
		"name": "Poison Sting",
		"type": "poison",
		"power": 5,
		"duration": 600,
		"energy": 7,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 3,
		"pvpEnergy": 8
	},
	"237": {
		"id": 237,
		"name": "Bubble",
		"type": "water",
		"power": 12,
		"duration": 1200,
		"energy": 14,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 8,
		"pvpEnergy": 11
	},
	"238": {
		"id": 238,
		"name": "Feint Attack",
		"type": "dark",
		"power": 10,
		"duration": 900,
		"energy": 9,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 6,
		"pvpEnergy": 6
	},
	"239": {
		"id": 239,
		"name": "Steel Wing",
		"type": "steel",
		"power": 11,
		"duration": 800,
		"energy": 6,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 7,
		"pvpEnergy": 5
	},
	"240": {
		"id": 240,
		"name": "Fire Fang",
		"type": "fire",
		"power": 12,
		"duration": 900,
		"energy": 8,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 8,
		"pvpEnergy": 5
	},
	"241": {
		"id": 241,
		"name": "Rock Smash",
		"type": "fighting",
		"power": 15,
		"duration": 1300,
		"energy": 10,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 9,
		"pvpEnergy": 7
	},
	"242": {
		"id": 242,
		"name": "Transform",
		"type": "normal",
		"power": 0,
		"duration": 2230,
		"energy": 0,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 0,
		"pvpEnergy": 0
	},
	"243": {
		"id": 243,
		"name": "Counter",
		"type": "fighting",
		"power": 12,
		"duration": 900,
		"energy": 8,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 8,
		"pvpEnergy": 7
	},
	"245": {
		"id": 245,
		"name": "Close Combat",
		"type": "fighting",
		"power": 100,
		"duration": 2300,
		"energy": 100,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 100,
		"pvpEnergy": 45
	},
	"246": {
		"id": 246,
		"name": "Dynamic Punch",
		"type": "fighting",
		"power": 90,
		"duration": 2700,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 90,
		"pvpEnergy": 50
	},
	"247": {
		"id": 247,
		"name": "Focus Blast",
		"type": "fighting",
		"power": 140,
		"duration": 3500,
		"energy": 100,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 140,
		"pvpEnergy": 75
	},
	"248": {
		"id": 248,
		"name": "Aurora Beam",
		"type": "ice",
		"power": 80,
		"duration": 3550,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 80,
		"pvpEnergy": 60
	},
	"249": {
		"id": 249,
		"name": "Charge Beam",
		"type": "electric",
		"power": 8,
		"duration": 1100,
		"energy": 15,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 5,
		"pvpEnergy": 11
	},
	"250": {
		"id": 250,
		"name": "Volt Switch",
		"type": "electric",
		"power": 14,
		"duration": 1600,
		"energy": 21,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 12,
		"pvpEnergy": 16
	},
	"251": {
		"id": 251,
		"name": "Wild Charge",
		"type": "electric",
		"power": 90,
		"duration": 2600,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 100,
		"pvpEnergy": 45
	},
	"252": {
		"id": 252,
		"name": "Zap Cannon",
		"type": "electric",
		"power": 140,
		"duration": 3700,
		"energy": 100,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 150,
		"pvpEnergy": 80
	},
	"253": {
		"id": 253,
		"name": "Dragon Tail",
		"type": "dragon",
		"power": 15,
		"duration": 1100,
		"energy": 9,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 9,
		"pvpEnergy": 10
	},
	"254": {
		"id": 254,
		"name": "Avalanche",
		"type": "ice",
		"power": 90,
		"duration": 2700,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 90,
		"pvpEnergy": 45
	},
	"255": {
		"id": 255,
		"name": "Air Slash",
		"type": "flying",
		"power": 14,
		"duration": 1200,
		"energy": 10,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 9,
		"pvpEnergy": 9
	},
	"256": {
		"id": 256,
		"name": "Brave Bird",
		"type": "flying",
		"power": 130,
		"duration": 2000,
		"energy": 100,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 130,
		"pvpEnergy": 55
	},
	"257": {
		"id": 257,
		"name": "Sky Attack",
		"type": "flying",
		"power": 80,
		"duration": 2000,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 80,
		"pvpEnergy": 45
	},
	"258": {
		"id": 258,
		"name": "Sand Tomb",
		"type": "ground",
		"power": 60,
		"duration": 4000,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 25,
		"pvpEnergy": 40
	},
	"259": {
		"id": 259,
		"name": "Rock Blast",
		"type": "rock",
		"power": 50,
		"duration": 2100,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 50,
		"pvpEnergy": 40
	},
	"260": {
		"id": 260,
		"name": "Infestation",
		"type": "bug",
		"power": 10,
		"duration": 1100,
		"energy": 14,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 6,
		"pvpEnergy": 12
	},
	"261": {
		"id": 261,
		"name": "Struggle Bug",
		"type": "bug",
		"power": 15,
		"duration": 1500,
		"energy": 15,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 9,
		"pvpEnergy": 8
	},
	"262": {
		"id": 262,
		"name": "Silver Wind",
		"type": "bug",
		"power": 70,
		"duration": 3700,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 45,
		"pvpEnergy": 45
	},
	"263": {
		"id": 263,
		"name": "Astonish",
		"type": "ghost",
		"power": 8,
		"duration": 1100,
		"energy": 14,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 5,
		"pvpEnergy": 9
	},
	"264": {
		"id": 264,
		"name": "Hex",
		"type": "ghost",
		"power": 10,
		"duration": 1200,
		"energy": 16,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 6,
		"pvpEnergy": 12
	},
	"265": {
		"id": 265,
		"name": "Night Shade",
		"type": "ghost",
		"power": 60,
		"duration": 2600,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 60,
		"pvpEnergy": 55
	},
	"266": {
		"id": 266,
		"name": "Iron Tail",
		"type": "steel",
		"power": 15,
		"duration": 1100,
		"energy": 7,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 9,
		"pvpEnergy": 6
	},
	"267": {
		"id": 267,
		"name": "Gyro Ball",
		"type": "steel",
		"power": 80,
		"duration": 3300,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 80,
		"pvpEnergy": 60
	},
	"268": {
		"id": 268,
		"name": "Heavy Slam",
		"type": "steel",
		"power": 70,
		"duration": 2100,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 70,
		"pvpEnergy": 50
	},
	"269": {
		"id": 269,
		"name": "Fire Spin",
		"type": "fire",
		"power": 14,
		"duration": 1100,
		"energy": 10,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 9,
		"pvpEnergy": 10
	},
	"270": {
		"id": 270,
		"name": "Overheat",
		"type": "fire",
		"power": 160,
		"duration": 4000,
		"energy": 100,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 130,
		"pvpEnergy": 55
	},
	"271": {
		"id": 271,
		"name": "Bullet Seed",
		"type": "grass",
		"power": 8,
		"duration": 1100,
		"energy": 14,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 5,
		"pvpEnergy": 13
	},
	"272": {
		"id": 272,
		"name": "Grass Knot",
		"type": "grass",
		"power": 90,
		"duration": 2600,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 90,
		"pvpEnergy": 50
	},
	"273": {
		"id": 273,
		"name": "Energy Ball",
		"type": "grass",
		"power": 90,
		"duration": 3900,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 90,
		"pvpEnergy": 55
	},
	"274": {
		"id": 274,
		"name": "Extrasensory",
		"type": "psychic",
		"power": 12,
		"duration": 1100,
		"energy": 12,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 8,
		"pvpEnergy": 10
	},
	"275": {
		"id": 275,
		"name": "Future Sight",
		"type": "psychic",
		"power": 120,
		"duration": 2700,
		"energy": 100,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 120,
		"pvpEnergy": 65
	},
	"277": {
		"id": 277,
		"name": "Outrage",
		"type": "dragon",
		"power": 110,
		"duration": 3900,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 110,
		"pvpEnergy": 60
	},
	"278": {
		"id": 278,
		"name": "Snarl",
		"type": "dark",
		"power": 12,
		"duration": 1100,
		"energy": 14,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 5,
		"pvpEnergy": 13
	},
	"279": {
		"id": 279,
		"name": "Crunch",
		"type": "dark",
		"power": 70,
		"duration": 3200,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 70,
		"pvpEnergy": 45
	},
	"280": {
		"id": 280,
		"name": "Foul Play",
		"type": "dark",
		"power": 70,
		"duration": 2000,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 70,
		"pvpEnergy": 45
	},
	"281": {
		"id": 281,
		"name": "Hidden Power",
		"type": "normal",
		"power": 15,
		"duration": 1500,
		"energy": 15,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 9,
		"pvpEnergy": 8
	},
	"283": {
		"id": 283,
		"name": "Waterfall",
		"type": "water",
		"power": 16,
		"duration": 1200,
		"energy": 8,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 12,
		"pvpEnergy": 8
	},
	"284": {
		"id": 284,
		"name": "Surf",
		"type": "water",
		"power": 65,
		"duration": 1700,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 65,
		"pvpEnergy": 40
	},
	"285": {
		"id": 285,
		"name": "Draco Meteor",
		"type": "dragon",
		"power": 150,
		"duration": 3600,
		"energy": 100,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 150,
		"pvpEnergy": 65
	},
	"287": {
		"id": 287,
		"name": "Yawn",
		"type": "normal",
		"power": 0,
		"duration": 1700,
		"energy": 15,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 0,
		"pvpEnergy": 12
	},
	"291": {
		"id": 291,
		"name": "Present",
		"type": "normal",
		"power": 5,
		"duration": 1300,
		"energy": 20,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 3,
		"pvpEnergy": 12
	},
	"296": {
		"id": 296,
		"name": "Frenzy Plant",
		"type": "grass",
		"power": 100,
		"duration": 2600,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 100,
		"pvpEnergy": 45
	},
	"298": {
		"id": 298,
		"name": "Blast Burn",
		"type": "fire",
		"power": 110,
		"duration": 3300,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 110,
		"pvpEnergy": 50
	},
	"299": {
		"id": 299,
		"name": "Hydro Cannon",
		"type": "water",
		"power": 90,
		"duration": 1900,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 80,
		"pvpEnergy": 40
	},
	"300": {
		"id": 300,
		"name": "Last Resort",
		"type": "normal",
		"power": 90,
		"duration": 2900,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 90,
		"pvpEnergy": 55
	},
	"301": {
		"id": 301,
		"name": "Meteor Mash",
		"type": "steel",
		"power": 100,
		"duration": 2600,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 100,
		"pvpEnergy": 50
	},
	"302": {
		"id": 302,
		"name": "Skull Bash",
		"type": "normal",
		"power": 130,
		"duration": 3100,
		"energy": 100,
		"energyBars": 1,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 130,
		"pvpEnergy": 75
	},
	"303": {
		"id": 303,
		"name": "Acid Spray",
		"type": "poison",
		"power": 20,
		"duration": 3000,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 20,
		"pvpEnergy": 50
	},
	"304": {
		"id": 304,
		"name": "Earth Power",
		"type": "ground",
		"power": 100,
		"duration": 3600,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 90,
		"pvpEnergy": 55
	},
	"305": {
		"id": 305,
		"name": "Crabhammer",
		"type": "water",
		"power": 85,
		"duration": 1900,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 75,
		"pvpEnergy": 50
	},
	"310": {
		"id": 310,
		"name": "Superpower",
		"type": "fighting",
		"power": 85,
		"duration": 3000,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 85,
		"pvpEnergy": 40
	},
	"311": {
		"id": 311,
		"name": "Fell Stinger",
		"type": "bug",
		"power": 50,
		"duration": 2200,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 20,
		"pvpEnergy": 35
	},
	"312": {
		"id": 312,
		"name": "Leaf Tornado",
		"type": "grass",
		"power": 45,
		"duration": 3100,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 45,
		"pvpEnergy": 40
	},
	"319": {
		"id": 319,
		"name": "Power-Up Punch",
		"type": "fighting",
		"power": 50,
		"duration": 2000,
		"energy": 33,
		"energyBars": 3,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 20,
		"pvpEnergy": 35
	},
	"320": {
		"id": 320,
		"name": "Charm",
		"type": "fairy",
		"power": 20,
		"duration": 1500,
		"energy": 11,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 16,
		"pvpEnergy": 6
	},
	"324": {
		"id": 324,
		"name": "Synchronoise",
		"type": "psychic",
		"power": 80,
		"duration": 2600,
		"energy": 50,
		"energyBars": 2,
		"isQuickMove": 0,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 80,
		"pvpEnergy": 50
	},
	"326": {
		"id": 326,
		"name": "Thunder Fang",
		"type": "electric",
		"power": 12,
		"duration": 1200,
		"energy": 16,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 8,
		"pvpEnergy": 5
	},
	"345": {
		"id": 345,
		"name": "Gust",
		"type": "flying",
		"power": 25,
		"duration": 2000,
		"energy": 20,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 1,
		"isExclusive": 0,
		"pvpPower": 16,
		"pvpEnergy": 12
	},
	"346": {
		"id": 346,
		"name": "Incinerate",
		"type": "fire",
		"power": 29,
		"duration": 2300,
		"energy": 20,
		"energyBars": 1,
		"isQuickMove": 1,
		"isLegacy": 0,
		"isExclusive": 0,
		"pvpPower": 15,
		"pvpEnergy": 20
	}
}